#!/bin/bash

# AUTOR: PABLO SIERRA VERSION: 1.0
#--------------------------------------------
# senseFi
#--------------------------------------------
#############################################
# Script senseFi
#############################################


sudo echo $$ > /sys/fs/cgroup/cpuset/grupoA/cgroup.procs


while true
do
	echo "sin fin"
	echo $$
done

